//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insheeption
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bondelag
    {
        public Bondelag()
        {
            this.Bonde = new HashSet<Bonde>();
        }
    
        public int bondelagID { get; set; }
        public int kommuneID { get; set; }
        public string navn { get; set; }
    
        public virtual ICollection<Bonde> Bonde { get; set; }
        public virtual Kommune Kommune { get; set; }
    }
}
