//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insheeption
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonde
    {
        public Bonde()
        {
            this.Saueflokk = new HashSet<Saueflokk>();
        }
    
        public int bondeID { get; set; }
        public int bondelagID { get; set; }
        public string navn { get; set; }
        public string etternavn { get; set; }
    
        public virtual Kontakt Kontakt { get; set; }
        public virtual login login { get; set; }
        public virtual ICollection<Saueflokk> Saueflokk { get; set; }
        public virtual Bondelag Bondelag { get; set; }
    }
}
