//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("IT1901Model", "bondeID_Kontakt", "Bonde", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Insheeption.Bonde), "Kontakt", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Insheeption.Kontakt), true)]
[assembly: EdmRelationshipAttribute("IT1901Model", "bondeID_login", "Bonde", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Insheeption.Bonde), "login", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Insheeption.login), true)]
[assembly: EdmRelationshipAttribute("IT1901Model", "bondeID_Saueflokk", "Bonde", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Insheeption.Bonde), "Saueflokk", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Insheeption.Saueflokk), true)]
[assembly: EdmRelationshipAttribute("IT1901Model", "bondelagID_Bonde", "Bondelag", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Insheeption.Bondelag), "Bonde", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Insheeption.Bonde), true)]
[assembly: EdmRelationshipAttribute("IT1901Model", "kommuneID_Bondelag", "Kommune", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Insheeption.Kommune), "Bondelag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Insheeption.Bondelag), true)]
[assembly: EdmRelationshipAttribute("IT1901Model", "sauID_Helse", "Sauer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Insheeption.Sauer), "Helse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Insheeption.Helse), true)]
[assembly: EdmRelationshipAttribute("IT1901Model", "kommuneID_Kontakt", "Kommune", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Insheeption.Kommune), "Kontakt", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Insheeption.Kontakt), true)]
[assembly: EdmRelationshipAttribute("IT1901Model", "sauID_Posisjon", "Sauer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Insheeption.Sauer), "Posisjon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Insheeption.Posisjon), true)]
[assembly: EdmRelationshipAttribute("IT1901Model", "flokkID_Sauer", "Saueflokk", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Insheeption.Saueflokk), "Sauer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Insheeption.Sauer), true)]

#endregion

namespace Insheeption
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IT1901Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IT1901Entities object using the connection string found in the 'IT1901Entities' section of the application configuration file.
        /// </summary>
        public IT1901Entities() : base("name=IT1901Entities", "IT1901Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IT1901Entities object.
        /// </summary>
        public IT1901Entities(string connectionString) : base(connectionString, "IT1901Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IT1901Entities object.
        /// </summary>
        public IT1901Entities(EntityConnection connection) : base(connection, "IT1901Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bonde> Bonde
        {
            get
            {
                if ((_Bonde == null))
                {
                    _Bonde = base.CreateObjectSet<Bonde>("Bonde");
                }
                return _Bonde;
            }
        }
        private ObjectSet<Bonde> _Bonde;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bondelag> Bondelag
        {
            get
            {
                if ((_Bondelag == null))
                {
                    _Bondelag = base.CreateObjectSet<Bondelag>("Bondelag");
                }
                return _Bondelag;
            }
        }
        private ObjectSet<Bondelag> _Bondelag;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Helse> Helse
        {
            get
            {
                if ((_Helse == null))
                {
                    _Helse = base.CreateObjectSet<Helse>("Helse");
                }
                return _Helse;
            }
        }
        private ObjectSet<Helse> _Helse;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Kommune> Kommune
        {
            get
            {
                if ((_Kommune == null))
                {
                    _Kommune = base.CreateObjectSet<Kommune>("Kommune");
                }
                return _Kommune;
            }
        }
        private ObjectSet<Kommune> _Kommune;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Kontakt> Kontakt
        {
            get
            {
                if ((_Kontakt == null))
                {
                    _Kontakt = base.CreateObjectSet<Kontakt>("Kontakt");
                }
                return _Kontakt;
            }
        }
        private ObjectSet<Kontakt> _Kontakt;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<login> login
        {
            get
            {
                if ((_login == null))
                {
                    _login = base.CreateObjectSet<login>("login");
                }
                return _login;
            }
        }
        private ObjectSet<login> _login;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Posisjon> Posisjon
        {
            get
            {
                if ((_Posisjon == null))
                {
                    _Posisjon = base.CreateObjectSet<Posisjon>("Posisjon");
                }
                return _Posisjon;
            }
        }
        private ObjectSet<Posisjon> _Posisjon;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Saueflokk> Saueflokk
        {
            get
            {
                if ((_Saueflokk == null))
                {
                    _Saueflokk = base.CreateObjectSet<Saueflokk>("Saueflokk");
                }
                return _Saueflokk;
            }
        }
        private ObjectSet<Saueflokk> _Saueflokk;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sauer> Sauer
        {
            get
            {
                if ((_Sauer == null))
                {
                    _Sauer = base.CreateObjectSet<Sauer>("Sauer");
                }
                return _Sauer;
            }
        }
        private ObjectSet<Sauer> _Sauer;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bonde EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBonde(Bonde bonde)
        {
            base.AddObject("Bonde", bonde);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bondelag EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBondelag(Bondelag bondelag)
        {
            base.AddObject("Bondelag", bondelag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Helse EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHelse(Helse helse)
        {
            base.AddObject("Helse", helse);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Kommune EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKommune(Kommune kommune)
        {
            base.AddObject("Kommune", kommune);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Kontakt EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKontakt(Kontakt kontakt)
        {
            base.AddObject("Kontakt", kontakt);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the login EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTologin(login login)
        {
            base.AddObject("login", login);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Posisjon EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPosisjon(Posisjon posisjon)
        {
            base.AddObject("Posisjon", posisjon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Saueflokk EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSaueflokk(Saueflokk saueflokk)
        {
            base.AddObject("Saueflokk", saueflokk);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sauer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSauer(Sauer sauer)
        {
            base.AddObject("Sauer", sauer);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IT1901Model", Name="Bonde")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bonde : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bonde object.
        /// </summary>
        /// <param name="bondeID">Initial value of the bondeID property.</param>
        /// <param name="bondelagID">Initial value of the bondelagID property.</param>
        public static Bonde CreateBonde(global::System.Int32 bondeID, global::System.Int32 bondelagID)
        {
            Bonde bonde = new Bonde();
            bonde.bondeID = bondeID;
            bonde.bondelagID = bondelagID;
            return bonde;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bondeID
        {
            get
            {
                return _bondeID;
            }
            set
            {
                if (_bondeID != value)
                {
                    OnbondeIDChanging(value);
                    ReportPropertyChanging("bondeID");
                    _bondeID = StructuralObject.SetValidValue(value, "bondeID");
                    ReportPropertyChanged("bondeID");
                    OnbondeIDChanged();
                }
            }
        }
        private global::System.Int32 _bondeID;
        partial void OnbondeIDChanging(global::System.Int32 value);
        partial void OnbondeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bondelagID
        {
            get
            {
                return _bondelagID;
            }
            set
            {
                OnbondelagIDChanging(value);
                ReportPropertyChanging("bondelagID");
                _bondelagID = StructuralObject.SetValidValue(value, "bondelagID");
                ReportPropertyChanged("bondelagID");
                OnbondelagIDChanged();
            }
        }
        private global::System.Int32 _bondelagID;
        partial void OnbondelagIDChanging(global::System.Int32 value);
        partial void OnbondelagIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String navn
        {
            get
            {
                return _navn;
            }
            set
            {
                OnnavnChanging(value);
                ReportPropertyChanging("navn");
                _navn = StructuralObject.SetValidValue(value, true, "navn");
                ReportPropertyChanged("navn");
                OnnavnChanged();
            }
        }
        private global::System.String _navn;
        partial void OnnavnChanging(global::System.String value);
        partial void OnnavnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String etternavn
        {
            get
            {
                return _etternavn;
            }
            set
            {
                OnetternavnChanging(value);
                ReportPropertyChanging("etternavn");
                _etternavn = StructuralObject.SetValidValue(value, true, "etternavn");
                ReportPropertyChanged("etternavn");
                OnetternavnChanged();
            }
        }
        private global::System.String _etternavn;
        partial void OnetternavnChanging(global::System.String value);
        partial void OnetternavnChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "bondeID_Kontakt", "Kontakt")]
        public Kontakt Kontakt
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kontakt>("IT1901Model.bondeID_Kontakt", "Kontakt").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kontakt>("IT1901Model.bondeID_Kontakt", "Kontakt").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kontakt> KontaktReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kontakt>("IT1901Model.bondeID_Kontakt", "Kontakt");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kontakt>("IT1901Model.bondeID_Kontakt", "Kontakt", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "bondeID_login", "login")]
        public login login
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<login>("IT1901Model.bondeID_login", "login").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<login>("IT1901Model.bondeID_login", "login").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<login> loginReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<login>("IT1901Model.bondeID_login", "login");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<login>("IT1901Model.bondeID_login", "login", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "bondeID_Saueflokk", "Saueflokk")]
        public EntityCollection<Saueflokk> Saueflokk
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Saueflokk>("IT1901Model.bondeID_Saueflokk", "Saueflokk");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Saueflokk>("IT1901Model.bondeID_Saueflokk", "Saueflokk", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "bondelagID_Bonde", "Bondelag")]
        public Bondelag Bondelag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bondelag>("IT1901Model.bondelagID_Bonde", "Bondelag").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bondelag>("IT1901Model.bondelagID_Bonde", "Bondelag").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bondelag> BondelagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bondelag>("IT1901Model.bondelagID_Bonde", "Bondelag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bondelag>("IT1901Model.bondelagID_Bonde", "Bondelag", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IT1901Model", Name="Bondelag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bondelag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bondelag object.
        /// </summary>
        /// <param name="bondelagID">Initial value of the bondelagID property.</param>
        /// <param name="kommuneID">Initial value of the kommuneID property.</param>
        public static Bondelag CreateBondelag(global::System.Int32 bondelagID, global::System.Int32 kommuneID)
        {
            Bondelag bondelag = new Bondelag();
            bondelag.bondelagID = bondelagID;
            bondelag.kommuneID = kommuneID;
            return bondelag;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bondelagID
        {
            get
            {
                return _bondelagID;
            }
            set
            {
                if (_bondelagID != value)
                {
                    OnbondelagIDChanging(value);
                    ReportPropertyChanging("bondelagID");
                    _bondelagID = StructuralObject.SetValidValue(value, "bondelagID");
                    ReportPropertyChanged("bondelagID");
                    OnbondelagIDChanged();
                }
            }
        }
        private global::System.Int32 _bondelagID;
        partial void OnbondelagIDChanging(global::System.Int32 value);
        partial void OnbondelagIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 kommuneID
        {
            get
            {
                return _kommuneID;
            }
            set
            {
                OnkommuneIDChanging(value);
                ReportPropertyChanging("kommuneID");
                _kommuneID = StructuralObject.SetValidValue(value, "kommuneID");
                ReportPropertyChanged("kommuneID");
                OnkommuneIDChanged();
            }
        }
        private global::System.Int32 _kommuneID;
        partial void OnkommuneIDChanging(global::System.Int32 value);
        partial void OnkommuneIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String navn
        {
            get
            {
                return _navn;
            }
            set
            {
                OnnavnChanging(value);
                ReportPropertyChanging("navn");
                _navn = StructuralObject.SetValidValue(value, true, "navn");
                ReportPropertyChanged("navn");
                OnnavnChanged();
            }
        }
        private global::System.String _navn;
        partial void OnnavnChanging(global::System.String value);
        partial void OnnavnChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "bondelagID_Bonde", "Bonde")]
        public EntityCollection<Bonde> Bonde
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bonde>("IT1901Model.bondelagID_Bonde", "Bonde");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bonde>("IT1901Model.bondelagID_Bonde", "Bonde", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "kommuneID_Bondelag", "Kommune")]
        public Kommune Kommune
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kommune>("IT1901Model.kommuneID_Bondelag", "Kommune").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kommune>("IT1901Model.kommuneID_Bondelag", "Kommune").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kommune> KommuneReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kommune>("IT1901Model.kommuneID_Bondelag", "Kommune");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kommune>("IT1901Model.kommuneID_Bondelag", "Kommune", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IT1901Model", Name="Helse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Helse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Helse object.
        /// </summary>
        /// <param name="sauID">Initial value of the sauID property.</param>
        /// <param name="tid">Initial value of the tid property.</param>
        public static Helse CreateHelse(global::System.Int32 sauID, global::System.String tid)
        {
            Helse helse = new Helse();
            helse.sauID = sauID;
            helse.tid = tid;
            return helse;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sauID
        {
            get
            {
                return _sauID;
            }
            set
            {
                if (_sauID != value)
                {
                    OnsauIDChanging(value);
                    ReportPropertyChanging("sauID");
                    _sauID = StructuralObject.SetValidValue(value, "sauID");
                    ReportPropertyChanged("sauID");
                    OnsauIDChanged();
                }
            }
        }
        private global::System.Int32 _sauID;
        partial void OnsauIDChanging(global::System.Int32 value);
        partial void OnsauIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tid
        {
            get
            {
                return _tid;
            }
            set
            {
                if (_tid != value)
                {
                    OntidChanging(value);
                    ReportPropertyChanging("tid");
                    _tid = StructuralObject.SetValidValue(value, false, "tid");
                    ReportPropertyChanged("tid");
                    OntidChanged();
                }
            }
        }
        private global::System.String _tid;
        partial void OntidChanging(global::System.String value);
        partial void OntidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> hjerteslag
        {
            get
            {
                return _hjerteslag;
            }
            set
            {
                OnhjerteslagChanging(value);
                ReportPropertyChanging("hjerteslag");
                _hjerteslag = StructuralObject.SetValidValue(value, "hjerteslag");
                ReportPropertyChanged("hjerteslag");
                OnhjerteslagChanged();
            }
        }
        private Nullable<global::System.Int32> _hjerteslag;
        partial void OnhjerteslagChanging(Nullable<global::System.Int32> value);
        partial void OnhjerteslagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> temperatur
        {
            get
            {
                return _temperatur;
            }
            set
            {
                OntemperaturChanging(value);
                ReportPropertyChanging("temperatur");
                _temperatur = StructuralObject.SetValidValue(value, "temperatur");
                ReportPropertyChanged("temperatur");
                OntemperaturChanged();
            }
        }
        private Nullable<global::System.Single> _temperatur;
        partial void OntemperaturChanging(Nullable<global::System.Single> value);
        partial void OntemperaturChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> alarm
        {
            get
            {
                return _alarm;
            }
            set
            {
                OnalarmChanging(value);
                ReportPropertyChanging("alarm");
                _alarm = StructuralObject.SetValidValue(value, "alarm");
                ReportPropertyChanged("alarm");
                OnalarmChanged();
            }
        }
        private Nullable<global::System.Boolean> _alarm;
        partial void OnalarmChanging(Nullable<global::System.Boolean> value);
        partial void OnalarmChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "sauID_Helse", "Sauer")]
        public Sauer Sauer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sauer>("IT1901Model.sauID_Helse", "Sauer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sauer>("IT1901Model.sauID_Helse", "Sauer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sauer> SauerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sauer>("IT1901Model.sauID_Helse", "Sauer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sauer>("IT1901Model.sauID_Helse", "Sauer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IT1901Model", Name="Kommune")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kommune : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Kommune object.
        /// </summary>
        /// <param name="kommuneID">Initial value of the kommuneID property.</param>
        /// <param name="kommunenavn">Initial value of the kommunenavn property.</param>
        /// <param name="nummer">Initial value of the nummer property.</param>
        public static Kommune CreateKommune(global::System.Int32 kommuneID, global::System.String kommunenavn, global::System.Int32 nummer)
        {
            Kommune kommune = new Kommune();
            kommune.kommuneID = kommuneID;
            kommune.kommunenavn = kommunenavn;
            kommune.nummer = nummer;
            return kommune;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 kommuneID
        {
            get
            {
                return _kommuneID;
            }
            set
            {
                if (_kommuneID != value)
                {
                    OnkommuneIDChanging(value);
                    ReportPropertyChanging("kommuneID");
                    _kommuneID = StructuralObject.SetValidValue(value, "kommuneID");
                    ReportPropertyChanged("kommuneID");
                    OnkommuneIDChanged();
                }
            }
        }
        private global::System.Int32 _kommuneID;
        partial void OnkommuneIDChanging(global::System.Int32 value);
        partial void OnkommuneIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String kommunenavn
        {
            get
            {
                return _kommunenavn;
            }
            set
            {
                OnkommunenavnChanging(value);
                ReportPropertyChanging("kommunenavn");
                _kommunenavn = StructuralObject.SetValidValue(value, false, "kommunenavn");
                ReportPropertyChanged("kommunenavn");
                OnkommunenavnChanged();
            }
        }
        private global::System.String _kommunenavn;
        partial void OnkommunenavnChanging(global::System.String value);
        partial void OnkommunenavnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nummer
        {
            get
            {
                return _nummer;
            }
            set
            {
                OnnummerChanging(value);
                ReportPropertyChanging("nummer");
                _nummer = StructuralObject.SetValidValue(value, "nummer");
                ReportPropertyChanged("nummer");
                OnnummerChanged();
            }
        }
        private global::System.Int32 _nummer;
        partial void OnnummerChanging(global::System.Int32 value);
        partial void OnnummerChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "kommuneID_Bondelag", "Bondelag")]
        public EntityCollection<Bondelag> Bondelag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bondelag>("IT1901Model.kommuneID_Bondelag", "Bondelag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bondelag>("IT1901Model.kommuneID_Bondelag", "Bondelag", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "kommuneID_Kontakt", "Kontakt")]
        public EntityCollection<Kontakt> Kontakt
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kontakt>("IT1901Model.kommuneID_Kontakt", "Kontakt");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kontakt>("IT1901Model.kommuneID_Kontakt", "Kontakt", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IT1901Model", Name="Kontakt")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kontakt : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Kontakt object.
        /// </summary>
        /// <param name="bondeID">Initial value of the bondeID property.</param>
        /// <param name="kommuneID">Initial value of the kommuneID property.</param>
        /// <param name="adresse">Initial value of the adresse property.</param>
        /// <param name="telefonnr">Initial value of the telefonnr property.</param>
        public static Kontakt CreateKontakt(global::System.Int32 bondeID, global::System.Int32 kommuneID, global::System.String adresse, global::System.Int32 telefonnr)
        {
            Kontakt kontakt = new Kontakt();
            kontakt.bondeID = bondeID;
            kontakt.kommuneID = kommuneID;
            kontakt.adresse = adresse;
            kontakt.telefonnr = telefonnr;
            return kontakt;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bondeID
        {
            get
            {
                return _bondeID;
            }
            set
            {
                if (_bondeID != value)
                {
                    OnbondeIDChanging(value);
                    ReportPropertyChanging("bondeID");
                    _bondeID = StructuralObject.SetValidValue(value, "bondeID");
                    ReportPropertyChanged("bondeID");
                    OnbondeIDChanged();
                }
            }
        }
        private global::System.Int32 _bondeID;
        partial void OnbondeIDChanging(global::System.Int32 value);
        partial void OnbondeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 kommuneID
        {
            get
            {
                return _kommuneID;
            }
            set
            {
                OnkommuneIDChanging(value);
                ReportPropertyChanging("kommuneID");
                _kommuneID = StructuralObject.SetValidValue(value, "kommuneID");
                ReportPropertyChanged("kommuneID");
                OnkommuneIDChanged();
            }
        }
        private global::System.Int32 _kommuneID;
        partial void OnkommuneIDChanging(global::System.Int32 value);
        partial void OnkommuneIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adresse
        {
            get
            {
                return _adresse;
            }
            set
            {
                OnadresseChanging(value);
                ReportPropertyChanging("adresse");
                _adresse = StructuralObject.SetValidValue(value, false, "adresse");
                ReportPropertyChanged("adresse");
                OnadresseChanged();
            }
        }
        private global::System.String _adresse;
        partial void OnadresseChanging(global::System.String value);
        partial void OnadresseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 telefonnr
        {
            get
            {
                return _telefonnr;
            }
            set
            {
                OntelefonnrChanging(value);
                ReportPropertyChanging("telefonnr");
                _telefonnr = StructuralObject.SetValidValue(value, "telefonnr");
                ReportPropertyChanged("telefonnr");
                OntelefonnrChanged();
            }
        }
        private global::System.Int32 _telefonnr;
        partial void OntelefonnrChanging(global::System.Int32 value);
        partial void OntelefonnrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> skriftstorrelse
        {
            get
            {
                return _skriftstorrelse;
            }
            set
            {
                OnskriftstorrelseChanging(value);
                ReportPropertyChanging("skriftstorrelse");
                _skriftstorrelse = StructuralObject.SetValidValue(value, "skriftstorrelse");
                ReportPropertyChanged("skriftstorrelse");
                OnskriftstorrelseChanged();
            }
        }
        private Nullable<global::System.Int32> _skriftstorrelse;
        partial void OnskriftstorrelseChanging(Nullable<global::System.Int32> value);
        partial void OnskriftstorrelseChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "bondeID_Kontakt", "Bonde")]
        public Bonde Bonde
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonde>("IT1901Model.bondeID_Kontakt", "Bonde").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonde>("IT1901Model.bondeID_Kontakt", "Bonde").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bonde> BondeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonde>("IT1901Model.bondeID_Kontakt", "Bonde");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bonde>("IT1901Model.bondeID_Kontakt", "Bonde", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "kommuneID_Kontakt", "Kommune")]
        public Kommune Kommune
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kommune>("IT1901Model.kommuneID_Kontakt", "Kommune").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kommune>("IT1901Model.kommuneID_Kontakt", "Kommune").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kommune> KommuneReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kommune>("IT1901Model.kommuneID_Kontakt", "Kommune");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kommune>("IT1901Model.kommuneID_Kontakt", "Kommune", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IT1901Model", Name="login")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class login : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new login object.
        /// </summary>
        /// <param name="bondeID">Initial value of the bondeID property.</param>
        public static login Createlogin(global::System.Int32 bondeID)
        {
            login login = new login();
            login.bondeID = bondeID;
            return login;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bondeID
        {
            get
            {
                return _bondeID;
            }
            set
            {
                if (_bondeID != value)
                {
                    OnbondeIDChanging(value);
                    ReportPropertyChanging("bondeID");
                    _bondeID = StructuralObject.SetValidValue(value, "bondeID");
                    ReportPropertyChanged("bondeID");
                    OnbondeIDChanged();
                }
            }
        }
        private global::System.Int32 _bondeID;
        partial void OnbondeIDChanging(global::System.Int32 value);
        partial void OnbondeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String epost
        {
            get
            {
                return _epost;
            }
            set
            {
                OnepostChanging(value);
                ReportPropertyChanging("epost");
                _epost = StructuralObject.SetValidValue(value, true, "epost");
                ReportPropertyChanged("epost");
                OnepostChanged();
            }
        }
        private global::System.String _epost;
        partial void OnepostChanging(global::System.String value);
        partial void OnepostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String passord
        {
            get
            {
                return _passord;
            }
            set
            {
                OnpassordChanging(value);
                ReportPropertyChanging("passord");
                _passord = StructuralObject.SetValidValue(value, true, "passord");
                ReportPropertyChanged("passord");
                OnpassordChanged();
            }
        }
        private global::System.String _passord;
        partial void OnpassordChanging(global::System.String value);
        partial void OnpassordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> huskmeg
        {
            get
            {
                return _huskmeg;
            }
            set
            {
                OnhuskmegChanging(value);
                ReportPropertyChanging("huskmeg");
                _huskmeg = StructuralObject.SetValidValue(value, "huskmeg");
                ReportPropertyChanged("huskmeg");
                OnhuskmegChanged();
            }
        }
        private Nullable<global::System.Int32> _huskmeg;
        partial void OnhuskmegChanging(Nullable<global::System.Int32> value);
        partial void OnhuskmegChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> admin
        {
            get
            {
                return _admin;
            }
            set
            {
                OnadminChanging(value);
                ReportPropertyChanging("admin");
                _admin = StructuralObject.SetValidValue(value, "admin");
                ReportPropertyChanged("admin");
                OnadminChanged();
            }
        }
        private Nullable<global::System.Int32> _admin;
        partial void OnadminChanging(Nullable<global::System.Int32> value);
        partial void OnadminChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "bondeID_login", "Bonde")]
        public Bonde Bonde
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonde>("IT1901Model.bondeID_login", "Bonde").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonde>("IT1901Model.bondeID_login", "Bonde").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bonde> BondeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonde>("IT1901Model.bondeID_login", "Bonde");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bonde>("IT1901Model.bondeID_login", "Bonde", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IT1901Model", Name="Posisjon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Posisjon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Posisjon object.
        /// </summary>
        /// <param name="sauID">Initial value of the sauID property.</param>
        /// <param name="tid">Initial value of the tid property.</param>
        /// <param name="flokkID">Initial value of the flokkID property.</param>
        public static Posisjon CreatePosisjon(global::System.Int32 sauID, global::System.String tid, global::System.String flokkID)
        {
            Posisjon posisjon = new Posisjon();
            posisjon.sauID = sauID;
            posisjon.tid = tid;
            posisjon.flokkID = flokkID;
            return posisjon;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sauID
        {
            get
            {
                return _sauID;
            }
            set
            {
                if (_sauID != value)
                {
                    OnsauIDChanging(value);
                    ReportPropertyChanging("sauID");
                    _sauID = StructuralObject.SetValidValue(value, "sauID");
                    ReportPropertyChanged("sauID");
                    OnsauIDChanged();
                }
            }
        }
        private global::System.Int32 _sauID;
        partial void OnsauIDChanging(global::System.Int32 value);
        partial void OnsauIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tid
        {
            get
            {
                return _tid;
            }
            set
            {
                if (_tid != value)
                {
                    OntidChanging(value);
                    ReportPropertyChanging("tid");
                    _tid = StructuralObject.SetValidValue(value, false, "tid");
                    ReportPropertyChanged("tid");
                    OntidChanged();
                }
            }
        }
        private global::System.String _tid;
        partial void OntidChanging(global::System.String value);
        partial void OntidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String flokkID
        {
            get
            {
                return _flokkID;
            }
            set
            {
                OnflokkIDChanging(value);
                ReportPropertyChanging("flokkID");
                _flokkID = StructuralObject.SetValidValue(value, false, "flokkID");
                ReportPropertyChanged("flokkID");
                OnflokkIDChanged();
            }
        }
        private global::System.String _flokkID;
        partial void OnflokkIDChanging(global::System.String value);
        partial void OnflokkIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String breddegrad
        {
            get
            {
                return _breddegrad;
            }
            set
            {
                OnbreddegradChanging(value);
                ReportPropertyChanging("breddegrad");
                _breddegrad = StructuralObject.SetValidValue(value, true, "breddegrad");
                ReportPropertyChanged("breddegrad");
                OnbreddegradChanged();
            }
        }
        private global::System.String _breddegrad;
        partial void OnbreddegradChanging(global::System.String value);
        partial void OnbreddegradChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lengdegrad
        {
            get
            {
                return _lengdegrad;
            }
            set
            {
                OnlengdegradChanging(value);
                ReportPropertyChanging("lengdegrad");
                _lengdegrad = StructuralObject.SetValidValue(value, true, "lengdegrad");
                ReportPropertyChanged("lengdegrad");
                OnlengdegradChanged();
            }
        }
        private global::System.String _lengdegrad;
        partial void OnlengdegradChanging(global::System.String value);
        partial void OnlengdegradChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "sauID_Posisjon", "Sauer")]
        public Sauer Sauer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sauer>("IT1901Model.sauID_Posisjon", "Sauer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sauer>("IT1901Model.sauID_Posisjon", "Sauer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sauer> SauerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sauer>("IT1901Model.sauID_Posisjon", "Sauer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sauer>("IT1901Model.sauID_Posisjon", "Sauer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IT1901Model", Name="Saueflokk")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Saueflokk : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Saueflokk object.
        /// </summary>
        /// <param name="flokkID">Initial value of the flokkID property.</param>
        /// <param name="bondeID">Initial value of the bondeID property.</param>
        /// <param name="antall">Initial value of the antall property.</param>
        public static Saueflokk CreateSaueflokk(global::System.Int32 flokkID, global::System.Int32 bondeID, global::System.Int32 antall)
        {
            Saueflokk saueflokk = new Saueflokk();
            saueflokk.flokkID = flokkID;
            saueflokk.bondeID = bondeID;
            saueflokk.antall = antall;
            return saueflokk;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 flokkID
        {
            get
            {
                return _flokkID;
            }
            set
            {
                if (_flokkID != value)
                {
                    OnflokkIDChanging(value);
                    ReportPropertyChanging("flokkID");
                    _flokkID = StructuralObject.SetValidValue(value, "flokkID");
                    ReportPropertyChanged("flokkID");
                    OnflokkIDChanged();
                }
            }
        }
        private global::System.Int32 _flokkID;
        partial void OnflokkIDChanging(global::System.Int32 value);
        partial void OnflokkIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bondeID
        {
            get
            {
                return _bondeID;
            }
            set
            {
                OnbondeIDChanging(value);
                ReportPropertyChanging("bondeID");
                _bondeID = StructuralObject.SetValidValue(value, "bondeID");
                ReportPropertyChanged("bondeID");
                OnbondeIDChanged();
            }
        }
        private global::System.Int32 _bondeID;
        partial void OnbondeIDChanging(global::System.Int32 value);
        partial void OnbondeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 antall
        {
            get
            {
                return _antall;
            }
            set
            {
                OnantallChanging(value);
                ReportPropertyChanging("antall");
                _antall = StructuralObject.SetValidValue(value, "antall");
                ReportPropertyChanged("antall");
                OnantallChanged();
            }
        }
        private global::System.Int32 _antall;
        partial void OnantallChanging(global::System.Int32 value);
        partial void OnantallChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "bondeID_Saueflokk", "Bonde")]
        public Bonde Bonde
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonde>("IT1901Model.bondeID_Saueflokk", "Bonde").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonde>("IT1901Model.bondeID_Saueflokk", "Bonde").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bonde> BondeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bonde>("IT1901Model.bondeID_Saueflokk", "Bonde");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bonde>("IT1901Model.bondeID_Saueflokk", "Bonde", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "flokkID_Sauer", "Sauer")]
        public EntityCollection<Sauer> Sauer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sauer>("IT1901Model.flokkID_Sauer", "Sauer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sauer>("IT1901Model.flokkID_Sauer", "Sauer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IT1901Model", Name="Sauer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sauer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sauer object.
        /// </summary>
        /// <param name="sauID">Initial value of the sauID property.</param>
        /// <param name="flokkID">Initial value of the flokkID property.</param>
        public static Sauer CreateSauer(global::System.Int32 sauID, global::System.Int32 flokkID)
        {
            Sauer sauer = new Sauer();
            sauer.sauID = sauID;
            sauer.flokkID = flokkID;
            return sauer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sauID
        {
            get
            {
                return _sauID;
            }
            set
            {
                if (_sauID != value)
                {
                    OnsauIDChanging(value);
                    ReportPropertyChanging("sauID");
                    _sauID = StructuralObject.SetValidValue(value, "sauID");
                    ReportPropertyChanged("sauID");
                    OnsauIDChanged();
                }
            }
        }
        private global::System.Int32 _sauID;
        partial void OnsauIDChanging(global::System.Int32 value);
        partial void OnsauIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 flokkID
        {
            get
            {
                return _flokkID;
            }
            set
            {
                OnflokkIDChanging(value);
                ReportPropertyChanging("flokkID");
                _flokkID = StructuralObject.SetValidValue(value, "flokkID");
                ReportPropertyChanged("flokkID");
                OnflokkIDChanged();
            }
        }
        private global::System.Int32 _flokkID;
        partial void OnflokkIDChanging(global::System.Int32 value);
        partial void OnflokkIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String navn
        {
            get
            {
                return _navn;
            }
            set
            {
                OnnavnChanging(value);
                ReportPropertyChanging("navn");
                _navn = StructuralObject.SetValidValue(value, true, "navn");
                ReportPropertyChanged("navn");
                OnnavnChanged();
            }
        }
        private global::System.String _navn;
        partial void OnnavnChanging(global::System.String value);
        partial void OnnavnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> fodselsdato
        {
            get
            {
                return _fodselsdato;
            }
            set
            {
                OnfodselsdatoChanging(value);
                ReportPropertyChanging("fodselsdato");
                _fodselsdato = StructuralObject.SetValidValue(value, "fodselsdato");
                ReportPropertyChanged("fodselsdato");
                OnfodselsdatoChanged();
            }
        }
        private Nullable<global::System.Int16> _fodselsdato;
        partial void OnfodselsdatoChanging(Nullable<global::System.Int16> value);
        partial void OnfodselsdatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notat
        {
            get
            {
                return _notat;
            }
            set
            {
                OnnotatChanging(value);
                ReportPropertyChanging("notat");
                _notat = StructuralObject.SetValidValue(value, true, "notat");
                ReportPropertyChanged("notat");
                OnnotatChanged();
            }
        }
        private global::System.String _notat;
        partial void OnnotatChanging(global::System.String value);
        partial void OnnotatChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "sauID_Helse", "Helse")]
        public EntityCollection<Helse> Helse
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Helse>("IT1901Model.sauID_Helse", "Helse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Helse>("IT1901Model.sauID_Helse", "Helse", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "sauID_Posisjon", "Posisjon")]
        public EntityCollection<Posisjon> Posisjon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Posisjon>("IT1901Model.sauID_Posisjon", "Posisjon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Posisjon>("IT1901Model.sauID_Posisjon", "Posisjon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IT1901Model", "flokkID_Sauer", "Saueflokk")]
        public Saueflokk Saueflokk
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Saueflokk>("IT1901Model.flokkID_Sauer", "Saueflokk").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Saueflokk>("IT1901Model.flokkID_Sauer", "Saueflokk").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Saueflokk> SaueflokkReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Saueflokk>("IT1901Model.flokkID_Sauer", "Saueflokk");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Saueflokk>("IT1901Model.flokkID_Sauer", "Saueflokk", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
