//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insheeption
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IT1901Entities : DbContext
    {
        public IT1901Entities()
            : base("name=IT1901Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bonde> Bonde { get; set; }
        public DbSet<Bondelag> Bondelag { get; set; }
        public DbSet<Helse> Helse { get; set; }
        public DbSet<Kommune> Kommune { get; set; }
        public DbSet<Kontakt> Kontakt { get; set; }
        public DbSet<login> login { get; set; }
        public DbSet<Posisjon> Posisjon { get; set; }
        public DbSet<Saueflokk> Saueflokk { get; set; }
        public DbSet<Sauer> Sauer { get; set; }
    }
}
