//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insheeption
{
    using System;
    using System.Collections.Generic;
    
    public partial class Helse
    {
        public int sauID { get; set; }
        public string tid { get; set; }
        public Nullable<int> hjerteslag { get; set; }
        public Nullable<float> temperatur { get; set; }
        public Nullable<bool> alarm { get; set; }
    
        public virtual Sauer Sauer { get; set; }
    }
}
