//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insheeption
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kommune
    {
        public Kommune()
        {
            this.Bondelag = new HashSet<Bondelag>();
            this.Kontakt = new HashSet<Kontakt>();
        }
    
        public int kommuneID { get; set; }
        public string kommunenavn { get; set; }
        public int nummer { get; set; }
    
        public virtual ICollection<Bondelag> Bondelag { get; set; }
        public virtual ICollection<Kontakt> Kontakt { get; set; }
    }
}
