//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insheeption
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakt
    {
        public int bondeID { get; set; }
        public int kommuneID { get; set; }
        public string adresse { get; set; }
        public int telefonnr { get; set; }
        public Nullable<int> skriftstorrelse { get; set; }
    
        public virtual Bonde Bonde { get; set; }
        public virtual Kommune Kommune { get; set; }
    }
}
