//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insheeption
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int bondeID { get; set; }
        public string epost { get; set; }
        public string passord { get; set; }
        public Nullable<int> huskmeg { get; set; }
        public Nullable<int> admin { get; set; }
    
        public virtual Bonde Bonde { get; set; }
    }
}
