//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insheeption
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saueflokk
    {
        public Saueflokk()
        {
            this.Sauer = new HashSet<Sauer>();
        }
    
        public int flokkID { get; set; }
        public int bondeID { get; set; }
        public int antall { get; set; }
    
        public virtual Bonde Bonde { get; set; }
        public virtual ICollection<Sauer> Sauer { get; set; }
    }
}
