//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insheeption
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sauer
    {
        public Sauer()
        {
            this.Helse = new HashSet<Helse>();
            this.Posisjon = new HashSet<Posisjon>();
        }
    
        public int sauID { get; set; }
        public int flokkID { get; set; }
        public string navn { get; set; }
        public Nullable<short> fodselsdato { get; set; }
        public string notat { get; set; }
    
        public virtual ICollection<Helse> Helse { get; set; }
        public virtual ICollection<Posisjon> Posisjon { get; set; }
        public virtual Saueflokk Saueflokk { get; set; }
    }
}
